#!/bin/bash
set -eo pipefail

main() {
  ensure  check_fish      install_fish
  ensure  check_fisher    install_fisher
  ensure  check_starship  install_starship
  ensure  check_fzf       install_fzf
  ensure  check_fish_git  install_fish_git
  ensure  check_gh        install_gh
}

check_fish() {
  command_exists fish
}
install_fish() {
  if command_exists brew; then
    brew install fish
  elif command_exists apt-get; then
    sudo apt-get install -y fish
  fi
}

check_fisher() {
  test -f ~/.config/fish/functions/fisher.fish
}
install_fisher() {
  fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
}

check_starship() {
  command_exists starship
}
install_starship() {
  if command_exists brew; then
    brew install starship
  else
    sh -c "$(curl -fsSL https://starship.rs/install.sh)" -- -y
  fi
}

check_fzf() {
  command_exists fzf
}
install_fzf() {
  if command_exists brew; then
    brew install fzf
  elif command_exists apt-get; then
    sudo apt-get install -y fzf
  fi
}

check_fish_git() {
  test -f ~/.config/fish/conf.d/git.fish
}
install_fish_git() {
  fish -c 'fisher install jhillyerd/plugin-git'
}

check_gh() {
  command_exists gh
}
install_gh() {
  if command_exists brew; then
    brew install gh
  elif command_exists apt-get; then
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo gpg --dearmor -o /usr/share/keyrings/githubcli-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
    sudo apt-get update
    sudo apt-get install gh -y
  fi
}
ensure() {
  if ! "$1"; then
    echo >&2 "=> $1 failed, running $2..."
    "$2"
  fi
  if ! "$1"; then
    echo >&2 "!! $1 still failed, aborted"
    exit 1
  fi
  echo >&2 "=> $1 passed"
}

command_exists() {
  command -v "$1" >/dev/null 2>&1
}

main
