[directory]
truncate_to_repo = false
style = "fg:#bbeeff"

[git_branch]
symbol = ""
style = "fg:#d7fc70"
format = "[on](fg:#8b8685) [$symbol$branch]($style) "

[cmd_duration]
format = "[took](fg:#8b8685) [$duration]($style) "
